"""OutcomeRecord - Output model for REQ-6 (Linear Project Tracking Integration)."""

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field


class OutcomeRecord(BaseModel):
    """Real-world outcome of grant opportunity pursuit.
    
    Generated by REQ-6 (Linear sync), consumed by REQ-8 (learning loop).
    """
    
    # Reference
    opportunity_id: str = Field(..., description="Links to GrantOpportunity.source_opportunity_id")
    
    # Outcome (per INTAKE BLOCK 7: funded, rejected, no-submit)
    outcome: str = Field(..., description="funded, rejected, no-submit, pending")
    outcome_date: Optional[datetime] = Field(None, description="Date outcome determined")
    
    # Linear tracking
    linear_project_id: Optional[str] = Field(None, description="Linear project ID")
    linear_project_url: Optional[str] = Field(None, description="Linear project URL")
    
    # Human notes
    human_notes: Optional[str] = Field(None, description="Human-entered context")
    
    # Metadata
    recorded_at: datetime = Field(default_factory=datetime.utcnow)
    
    class Config:
        json_schema_extra = {
            "example": {
                "opportunity_id": "HHS-OS-24-001",
                "outcome": "no-submit",
                "outcome_date": "2024-02-20T00:00:00Z",
                "linear_project_id": "VTK-100",
                "linear_project_url": "https://linear.app/vtkl/project/VTK-100",
                "human_notes": "8(a) certification blocker confirmed",
                "recorded_at": "2024-02-20T00:00:00Z"
            }
        }
