"""TeamingPartner - Output model for REQ-7 (Teaming Partner Intelligence Module)."""

from typing import Optional
from pydantic import BaseModel, Field


class TeamingPartner(BaseModel):
    """Teaming partner recommendation.
    
    Generated by REQ-7, consumed by REQ-4 (reports).
    """
    
    # Reference
    opportunity_id: str = Field(..., description="Links to GrantOpportunity.source_opportunity_id")
    
    # Partner details (per INTAKE BLOCK 3: name, role, rationale, source only)
    partner_name: str = Field(..., description="Organization name")
    partner_role: str = Field(..., description="Role: research, subcontractor, teaming, etc.")
    rationale: str = Field(..., description="Why this partner is relevant")
    source: str = Field(..., description="hardcoded or usaspending")
    
    # Additional context from USAspending.gov
    naics_codes: list[str] = Field(default_factory=list, description="NAICS codes (if from USAspending)")
    past_agency_work: Optional[str] = Field(None, description="Past work with agency (if from USAspending)")
    
    class Config:
        json_schema_extra = {
            "example": {
                "opportunity_id": "NSF-25-001",
                "partner_name": "University of Hawaii at Mānoa",
                "partner_role": "Research Partner",
                "rationale": "NSF CSSI pattern — academic research institution with cyberinfrastructure expertise",
                "source": "hardcoded",
                "naics_codes": [],
                "past_agency_work": None
            }
        }
