"""VerdictReport - Output model for REQ-4 (Opportunity Report & Verdict Card Generator)."""

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field


class RoadmapPhase(BaseModel):
    """Phase-gated next step."""
    phase_number: int
    description: str
    owner: str = Field(..., description="human or automated")
    estimated_duration: Optional[str] = None


class VerdictReport(BaseModel):
    """Complete opportunity assessment report.
    
    Generated by REQ-4, consumed by REQ-5 (Slack), REQ-6 (Linear).
    """
    
    # Reference
    opportunity_id: str = Field(..., description="Links to GrantOpportunity.source_opportunity_id")
    
    # Five components (per INTAKE BLOCK 5)
    # Component 1: Verdict Card
    verdict: str = Field(..., description="GO, SHAPE, MONITOR, NO-GO")
    composite_score: float = Field(..., ge=0, le=100)
    verdict_rationale: str = Field(..., description="Rationale with evidence quotes")
    
    # Component 2: Executive Summary (exactly 3 sentences per acceptance criteria)
    executive_summary: str = Field(..., description="Exactly 3 sentences with eligibility evidence")
    
    # Component 3: Risk Assessment
    risk_assessment: str = Field(..., description="Timeline risks, blockers, missing requirements")
    
    # Component 4: Strategic Roadmap (GO/SHAPE only, per acceptance criteria)
    strategic_roadmap: Optional[list[RoadmapPhase]] = Field(None, description="Phase-gated next steps")
    
    # Component 5: One-Pager Pitch (GO/SHAPE only)
    one_pager_pitch: Optional[str] = Field(None, description="VTKL messaging with 'execution engine', 'purpose-built solutions'")
    
    # Metadata
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    status: str = Field(default="awaiting_human_approval", description="Report approval status")
    
    class Config:
        json_schema_extra = {
            "example": {
                "opportunity_id": "HHS-OS-24-001",
                "verdict": "NO-GO",
                "composite_score": 39.0,
                "verdict_rationale": "Despite strong mission fit (90/100) and technical alignment (85/100), opportunity requires 8(a) certification which VTKL does not currently hold, resulting in eligibility score of 0/100.",
                "executive_summary": "HHS seeks AI/ML solutions for healthcare data analysis with $1M-$2.5M award range. VTKL has strong technical capabilities but does not meet 8(a) certification requirement. Opportunity is not eligible for pursuit.",
                "risk_assessment": "**Blocker:** 8(a) certification required — VTKL not certified. **Timeline risk:** None (opportunity not pursuable). **Missing requirements:** 8(a) Small Business certification.",
                "strategic_roadmap": None,
                "one_pager_pitch": None,
                "generated_at": "2024-02-20T00:00:00Z",
                "status": "awaiting_human_approval"
            }
        }
